[package]
name = "solobserve-anchor"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
solobserve-sdk = { path = "../solobserve-sdk" }
trybuild = "1"
