[package]
name = "alerter"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
solobserve-config.workspace = true
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
chrono.workspace = true
sha2.workspace = true
hex = "0.4"
solobserve-dsl.workspace = true
prometheus.workspace = true
axum.workspace = true
aes-gcm = "0.10"
uuid.workspace = true
lettre = { version = "0.11", default-features = false, features = ["builder", "smtp-transport", "tokio1", "tokio1-rustls-tls"] }
hmac = "0.12"
