[package]
name = "metrics-scraper"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
reqwest.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true
clickhouse.workspace = true
serde.workspace = true
serde_json.workspace = true
prometheus-parse = "0.2"
solobserve-config.workspace = true
solobserve-storage.workspace = true
